### ISSUE TITLE
obstruction test

### ISSUE THREAD

**Issue by adespawn** [baktrius/MIMUW_PW_2nd_lab_assignment#6]
https://github.com/baktrius/MIMUW_PW_2nd_lab_assignment/blob/b78b5de1f50bd887183c5b84f2086fa1b329d9ac/examples/obstruction.c#L21-L23

O ile ten test jest poprawny, to czy jego zamysłem nie było coś nieco innego (np. sprawdzenie też innych bajtów niż bajt 790ty)?

**Comment by baktrius** [comment]
Na razie nie widzę problemu. Test w procesie 0 najpierw wysyła dużo danych do procesu 1, a później się synchronizuje.
W procesie 1 kolejność jest zamieniona tzn. najpierw się synchronizujemy, później odbieramy dużo danych.
Tym samym jeśli implementacja naiwnie pisze i odczytuje tylko polegając na buforze zapewnionym przez kanały to on się przepełni i test zakończy się timeoutem.
Sprawdzanie co 790 bajtu jest symbolicznym sprawdzeniem, że istotnie wysłaliśmy wszystkie dane, a nie np. ich pierwsze 512 bajtów. Oczywiście nie można na tym polegać i nie chodzi o to aby wysyłać tylko co 790 bajt celem uniknięcia przepełnienia bufora (nie tędy droga).

**Comment by adespawn** [comment]
Gdyby jeszcze ta pętla sprawdzała co 790 bajt zamiast sprawdzając wiele razy 790 bajt to zgodziłbym się z tą odpowiedzą.

**Comment by baktrius** [comment]
Tak, masz rację. Spróbuję to poprawić w wolnej chwili.
